language: node_js
node_js:
  - node
  - lts/*
  - 8
  - 9
  - 10
cache: npm
services:
  - mysql
  - redis-server
before_install:
  - mysql -e 'CREATE DATABASE csmm;'
install:
  -  npm install
script:
  - npm test
  - npm run coverage
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "dist/cpm-map-*.tgz"
  api_key: $GITHUB_TOKEN
  on:
    branch: master
    tags: true